### PR TITLE
Imgur indirect images (imgur.com/dVsd8j3), imgur albums support, and multireddit support.

### PR DESCRIPTION
**Pull request by cameronehrlich**
... I also did some stuff to improve the default number_of_files_to_download wonkyness.  I did just kind of whip this together really fast so I understand if you don't want to pull it in its current form.  But I figured I'd offer it up!

P.S. The thought crossed my mind that this might be a pretty baddass browser extension, but that'd be a lot of work.

### CODE REVIEW

**Comment by bluquar** [comment]
This is great, the imgur album and multireddit support looks good. 

There is one bug I notice that is stopping me from merging this in its current form. When a user changes the "Files to Download" field in the GUI, the settings object does not change, so the configuration file is not updated properly when the user clicks "Save". This is mainly because you removed the code in `gui.timer`:

    if self.number_of_files_entry.get() != self.prev_entry:
        num = self._int_in_entry(self.number_of_files_entry)
        if num is not None:
            self.subreddit.num_files = num

You mentioned trying to fix weird behavior with the default number of files - what exactly was that behavior?

**Comment by cameronehrlich** [comment]
For me at least it was flickering and between values when I tried to change it...or something like that haha.  I'll try to take a look at fixing this soon, I do think however this might be something worth brainstorming on a better solution. I feel like long-polling that entry field is not necessarily the best option.  Perhaps the python GUI library you're using offers some kind of "on-change" callback?

**Comment by blade2005** [comment]
Any luck with this?
 I know this issue is 2 years old at this point but IFTTT isn't cutting it for me and I found this project

**Comment by cameronehrlich** [comment]
@blade2005 I never got around to fixing the issue @bluquar pointed out... Do you wanna try to fix it?  If not I might be able to spend some time on it next week.

**Comment by blade2005** [comment]
I will try to look at it either this week or over the weekend

**Pull request closed without merging**
